### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by asoutoiglesias** [bolverk/huji-rich#23]
Hi.

We are having issues with Makefile.
We get this message
fatal error: hdf5.h: No such file or directory
but the file is in
/usr/include/hdf5/serial/

I presume paths may need some tuning. 

Could you help? Thx!

**Comment by eladtan** [comment]
Hi,

I'd be happy to help you with installing and running the code.

Can you pls write exactly what you typed during the install and what the output was?

Elad

**Comment by asoutoiglesias** [comment]
Thank you for answering. We (I am not good at these things but a student is helping me and he thinks there maybe something that works for your folder tree structure but not for mine nor his) tried both with make and with the python script homebrew_makefile.py

We have Hdf5 and boost installed 

I work with Ubuntu 16.04.1

This is what we get.

make
mkdir -p `dirname library_production/tessellation/hdf5_logger.o`
g++ -c -O3 -march=native -Werror -Wall -Wextra -pedantic -Wno-long-long -Wfatal-errors -Weffc++ -Wshadow -Wmissing-declarations -Wconversion source/tessellation/hdf5_logger.cpp -o library_production/tessellation/hdf5_logger.o
In file included from /usr/include/hdf5/serial/H5Cpp.h:20:0,
                 from source/tessellation/../misc/hdf5_utils.hpp:11,
                 from source/tessellation/hdf5_logger.cpp:5:
/usr/include/hdf5/serial/H5Include.h:17:18: fatal error: hdf5.h: No such file or directory
compilation terminated.
Makefile:45: recipe for target 'library_production/tessellation/hdf5_logger.o' failed
make: *** [library_production/tessellation/hdf5_logger.o] Error 1

WITH THE PYTHON, similar outcome. 

 python homebrew_makefile.py
In file included from /usr/include/hdf5/serial/H5Cpp.h:20:0,
                 from source/tessellation/../misc/hdf5_utils.hpp:11,
                 from source/tessellation/hdf5_logger.cpp:5:
/usr/include/hdf5/serial/H5Include.h:17:18: fatal error: hdf5.h: No such file or directory
compilation terminated.
Traceback (most recent call last):
  File "homebrew_makefile.py", line 181, in <module>
    main()
  File "homebrew_makefile.py", line 174, in main
    efficient_compile(fname,lname)
  File "homebrew_makefile.py", line 143, in efficient_compile
    sensitive_compile(fname,lname)
  File "homebrew_makefile.py", line 134, in sensitive_compile
    strict_compile(fname, lname)
  File "homebrew_makefile.py", line 99, in strict_compile
    raise NameError('problem with compilation')
NameError: problem with compilation

THANK YOU

**Comment by eladtan** [comment]
Did you type before?

> make set_environ_vars.sh && \`cat set_environ_vars.sh\`

This would download a new version of boost and hdf5, install them and set the path. This should be the simplest option by far.

Otherwise, f you don't want this then add the following path variables:
CPLUS_INCLUDE_PATH= needs to point to the boost home directory,hdf5 include directory

HDF5_LIB_PATH=needs to point to the hdf5 lib directory
LD_LIBRARY_PATH=needs to point to the hdf5 lib directory and to the clipper library 
LD_PATH=same as LD_LIBRARY_PATH
RICH_ROOT= needs to point to the main huji-rich directory

you also need to download the clipper package from  http://sourceforge.net/projects/polyclipping/files/latest/download?source=files and compile it as a library.

**Comment by changyoonpark** [comment]
Hi, I am Chang, a student working with Antonio. We tried to get the code compiled, but are still struggling to get the code to compile. 

1. The version of the HDF5 in the makefile on the Github repo is out of date. It needs to be updated to the latest version. Thus, using the option "set_environ_vars.sh" does not work.

2. When trying to compile code using "python run_tests.py [folder]", the compiler throws various errors for various .cpp files, under the default settings you have in the "homebrew_makefile.py" file. Few of them were:
  - no default case in switch. (We had to remove some compiler options to get rid of it.)
  - deprecated delcarations. (We had to add a -Wno-deprecated-declarations option to get rid of it)

3. There was a file looking in the wrong directory for BOOST libraries.
  - "source/tessellation/find_affected_cells.cpp" looks for the "foreach.hpp" file in the wrong directory ("boost/foreach.hpp"). If we manually fix the directory to the correct location, it looks for the definition "BOOST_FOREACH", which is not defined in "foreach.hpp" and throws a compiler error again. 

At this point, we did not want to manually modify any code before we hear from you regarding the problems. It will be greatly appreciated if you can provide some guidance.

Thanks!
Chang

**Comment by eladtan** [comment]
Change in the makefile  so it looks for the newest hdf5 version's source file.
What version of boost do you have?

**Comment by bolverk** [comment]
I changed the makefile so it would look for the newest version of hdf5. Try pulling and then running set_environ_vars.sh again.

**Comment by changyoonpark** [comment]
Hi, Thanks for your reply. Here is what we are going through at this point :

1. We rm -rf'd everything we have.
2. "git clone https://github.com/bolverk/huji-rich.git"
3. Inside the "huji-rich" folder, we did "make set_environ_vars.sh && `cat set_environ_vars.sh`" (No errors)
4. Then, inside the "huji-rich" folder, we did "make" (No errors)
5. Now, we tried to run a test. inside the "tests" folder, we did 
    "python run_tests.py newtonian/two_dimensional/gresho_vortex_2o/".
6. This is what we get : 

![error](https://cloud.githubusercontent.com/assets/13445580/23036261/008cf0f0-f437-11e6-9049-ec7f2dce403c.png)

7. Trying the other examples, we also get the same error.
8. The compiler is looking for "librich.a" in the wrong folder. "librich.a" is actually located in "/library_production", not "/library".
9. Me and Antonio agreed that it would be more constructive to solve this problem with you, instead of modifying any code. This way, we can go through all the issues step-by-step.

Thank you very much. We are really excited about running your code.

Regards,
Chang

**Comment by eladtan** [comment]
Try typing just make in the tests directory

**Comment by changyoonpark** [comment]
Hi, Thanks for the reply.

When we try make inside "/tests", we get this error : 

![h5py_error](https://cloud.githubusercontent.com/assets/13445580/23037219/66667c86-f43a-11e6-82fc-a115a2cac3ef.png)

It seems like it requires h5py. Is this python library also required for the installation?

Thank you.
Chang

**Comment by eladtan** [comment]
The module is required to run the tests since python needs to read the hdf5
files.
It is not needed to run the code.
Installing this module should be easy and it is a good thing to do.

**Comment by changyoonpark** [comment]
Thanks for your support.

We installed h5py, and successfully ran make without any errors.
We now have a new folder named "production", with each subfolder looks something like this : 

![drivenwaves](https://cloud.githubusercontent.com/assets/13445580/23040488/568e4d46-f446-11e6-8884-6329c7a2558e.png)

I am assuming the test case passed, and the files are the output files for test.
I'm confused about the .exe file. What is the purpose of this executable?

Thanks, I think we are getting closer to running your code.

Regards,
Chang

**Comment by eladtan** [comment]
test.exe is the executable that was created of our code. It is the
executable that was run for the tests.
Our code requires you to create a main file for each run, so each time you
want a new test you have a new executable.

**Comment by asoutoiglesias** [comment]
Thank you Elad.

We thought it would be nice for starting to run some of the tests cases of your 2014 paper:

RICH: OPEN SOURCE HYDRODYNAMIC SIMULATION ON A MOVING VORONOI MESH

The easiest for classical dynamics guys like myself are the Rayleigh Taylor or the KH instabilities. However, it seems there are not examples for these.

There is for the Gresho Vortex, which is treated in your paper and documented in detail in 2010 Springel's paper, which you cite.

Following what you indicate in file mainpage.h

**To run just a single test and retain the temporary folder, use
 *
 * \code 
 * ./run_test.py [path to folder]
 * \endcode**

I type in folder /huji-rich/tests

python run_tests.py newtonian/two_dimensional/gresho_vortex_2o/

and python throws this screen with errors.

![error1](https://cloud.githubusercontent.com/assets/17180399/23098505/ac17b5ae-f603-11e6-9014-d00f7692f405.jpg)

A new folder  

temp_newtonian_two_dimensional_gresho_vortex_2o

has appeared, with the following contents. 

![error2](https://cloud.githubusercontent.com/assets/17180399/23098515/1903f218-f604-11e6-980f-63899418bb11.jpg)

I think we are not far. 

Your help would be appreciated. 

Thank you.

**Comment by eladtan** [comment]
I updated the MAINPAGE,h file. Only the wiki is relevant.
The simplest way is to create a new directory in the runs directory and to copy the files there.
from the run directory type
`make TARGET=DIR_NAME`
and it will compile and run the executable from a directory called temp_DIR_NAME
What project do you have in mind for the code?

**Comment by asoutoiglesias** [comment]
Thank you. 

We had overlooked the Wiki. Unfortunate. Sorry.

We are interested in coupling Voronoi and SPH for free surface flows, but that is a long shot yet.  

We have prototyped a code in MATLAB and are now migrating to C. 

We are very interested in running yours and taking it as reference. It seems to us you have done a very nice work and the papers are very informative.

**Comment by asoutoiglesias** [comment]
We have followed the instructions in
https://github.com/bolverk/huji-rich/wiki/Tests
and 
https://github.com/bolverk/huji-rich/wiki/Visualisation-and-Analysis

A file final.h5 is generated, where the output is expected (?). This is the error the script hdf5_voronoi_plot.py throws. 
![_error3](https://cloud.githubusercontent.com/assets/17180399/23200077/30f03cbc-f887-11e6-8db3-d2db75689b0d.jpg)

Help would be appreciated. 

Thank you very much.

**Comment by eladtan** [comment]
That python script needs to be updated.
Do you have access to matlab? I can give you a script that works in matlab.
Alternatively, you can just read the hdf5 data yourself in python and plot the data however you like.

**Comment by asoutoiglesias** [comment]
Thank you. 

I have access to MATLAB.

There is this folder where you have a set of MATLAB functions. 

![xxerror3](https://cloud.githubusercontent.com/assets/17180399/23200414/0ab21d5c-f889-11e6-83dc-4fd50c117e6e.jpg)

Is there a function among these to plot the results of this case we are dealing with?  Which would be the command in MATLAB to do so.

One I can see results for one case, I think I can make my way through how this is set up. 

Thank you and sorry for bothering you with these matters.

**Comment by eladtan** [comment]
use read_hdf.m

**Comment by asoutoiglesias** [comment]
Thank you. 

This is what I get with read_hdf.m  if I execute

[X,Pressure,Density,Points,xVelocity,yVelocity,time,Tracers,NumberOfPointsInCell]=read_hdf("final.h5",1,1,1)

in MATLAB, in huji-rich/tests/production/newtonian/two_dimensional/gresho_vortex_2o/  folder

Not very interesting, and with the cells barely visible,  but enough to start working. 

Thank you. 

![_gv](https://cloud.githubusercontent.com/assets/17180399/23220761/d050a814-f8d7-11e6-8f66-1764b66b8920.jpg)

**Comment by changyoonpark** [comment]
Hi, we slightly updated the python script to accommodate the h5 data.

`hdf5_voronoi_plot.py`

```
import h5py
import pylab
import numpy
import matplotlib
import sys
import argparse

parser = argparse.ArgumentParser(description='Displays snapshot of the hydrodynamic simualation')
parser.add_argument("file_name",
                    help="path to snapshot file")
parser.add_argument("field",
                    help="Name of hydrodynamic variable")
args = parser.parse_args()

h5f = h5py.File(args.file_name)

z_list = h5f['hydrodynamic'][args.field]
vert_x_raw = numpy.array(h5f['geometry']['x_vertices'])
vert_y_raw = numpy.array(h5f['geometry']['y_vertices'])
vert_n_raw = h5f['geometry']['n_vertices']
vert_idx_list = numpy.cumsum(vert_n_raw)

z_range = max(z_list) - min(z_list) + 1e-15
z_min = min(z_list)
z_scaled = [(z-z_min)/z_range for z in z_list]

print(z_scaled)
for i in range(len(vert_n_raw)):
    upbound = vert_idx_list[i]
    if i==0:
        lowbound = 0
    else:
        lowbound = vert_idx_list[i-1]

    pylab.fill(vert_x_raw[int(lowbound):int(upbound)],
               vert_y_raw[int(lowbound):int(upbound)],
               fc=matplotlib.cm.jet(z_scaled[i]),
               ec='None')

pylab.title(args.field)
ax, _ = matplotlib.colorbar.make_axes(pylab.gca())
print(min(z_list))
print(max(z_list))
matplotlib.colorbar.ColorbarBase(ax,norm=matplotlib.colors.Normalize(vmin=min(z_list),vmax=max(z_list)),cmap=matplotlib.cm.jet)

pylab.show()

```

(Demo for Gresho 2D)

![figure_1](https://cloud.githubusercontent.com/assets/13445580/23281121/dce8742c-f9d0-11e6-8e35-63fac699a5a8.png)

We will now start working with the code, we will keep you updated in the future, if you are interested.

Thanks,
Chang.
